name = "StreamMacros"
uuid = "1418a599-1564-4a75-98e9-b890cf8b552f"
authors = ["Alvaro de Diego"]
version = "0.1.2"

[deps]
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
SymEngine = "123dc426-2d89-5057-bbad-38513e3affd8"

[compat]
DiffEqBase = "6"
StaticArrays = "0.10, 0.11, 0.12, 1.0"
SymEngine = "0.6, 0.7, 0.8"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
